# Generated by Django 2.1.3 on 2018-12-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='summary',
        ),
        migrations.AddField(
            model_name='sala',
            name='Audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sala',
            name='Enregistraments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sala',
            name='MicroTaula',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sala',
            name='Microsensefils',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sala',
            name='PC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sala',
            name='PantallaLed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sala',
            name='Vídeoconferencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sala',
            name='Wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sala',
            name='status',
            field=models.CharField(blank=True, choices=[('t', 'Taller'), ('a', 'Auditori'), ('r', 'Reunió')], default='r', help_text='Disposició de la sala', max_length=1),
        ),
        migrations.AlterField(
            model_name='sala',
            name='capacitat',
            field=models.IntegerField(help_text='Màxim aforament'),
        ),
    ]
