# Generated by Django 2.1.3 on 2018-12-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20181204_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='Audio',
            field=models.BooleanField(default=False, verbose_name="Disposa d' audio"),
        ),
        migrations.AlterField(
            model_name='sala',
            name='Enregistraments',
            field=models.BooleanField(default=False, verbose_name='Pot fer enregistraments'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='MicroTaula',
            field=models.BooleanField(default=False, verbose_name='Micro de taula'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='Microsensefils',
            field=models.BooleanField(default=False, verbose_name='Micro sense fils'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='PC',
            field=models.BooleanField(default=False, verbose_name='Disposa de PC'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='PantallaLed',
            field=models.BooleanField(default=False, verbose_name='Disposa de monitor'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='Vídeoconferencia',
            field=models.BooleanField(default=False, verbose_name='Equip de videoconfrencia'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='Wifi',
            field=models.BooleanField(default=False, verbose_name='Disposa de Wifi'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='projector',
            field=models.BooleanField(default=False, verbose_name='Disposa de projector'),
        ),
    ]
