# Generated by Django 2.1.3 on 2018-12-05 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0003_auto_20181205_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peticions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID únic per aquesta petició', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('data_inici', models.DateField(blank=True)),
                ('data_final', models.DateField(blank=True)),
                ('peticionari', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_inici'],
            },
        ),
        migrations.AlterField(
            model_name='sala',
            name='status',
            field=models.CharField(choices=[('t', 'Taller'), ('a', 'Auditori'), ('r', 'Reunió')], default='r', help_text='Disposició de la sala', max_length=1),
        ),
    ]
