# Generated by Django 2.1.3 on 2018-12-05 10:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0004_auto_20181205_1125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peticions',
            new_name='Peticio',
        ),
    ]
