# Generated by Django 2.1.3 on 2018-12-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20181205_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peticio',
            name='imprint',
        ),
        migrations.AddField(
            model_name='peticio',
            name='assitents',
            field=models.IntegerField(default=0, help_text="Nombre d'assistents"),
        ),
        migrations.AlterField(
            model_name='peticio',
            name='data_final',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='peticio',
            name='data_inici',
            field=models.DateTimeField(blank=True),
        ),
    ]
