# Generated by Django 2.1.3 on 2018-12-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20181205_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticio',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
