# Generated by Django 2.1.3 on 2019-01-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20181212_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peticio',
            old_name='assitents',
            new_name='assistents',
        ),
    ]
