# Generated by Django 2.1.3 on 2019-01-23 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20190123_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticio',
            name='data_peticio',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
