# Generated by Django 2.1.3 on 2019-02-05 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_peticio_data_peticio'),
    ]

    operations = [
        migrations.AddField(
            model_name='concesio',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 23, 9, 9872)),
        ),
        migrations.AddField(
            model_name='concesio',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 23, 9, 9872)),
        ),
    ]
